#Travis - 2/16/18
language: ruby
rvm:
  - 2.3.3
install: gem install jekyll jekyll-redirect-from s3_website
script: jekyll build
after_success: 
  - bash postbuild.sh
  - s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false
