---
title: GoAIA - Sports Performance
timezone: UTC
collections:
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
    permalink: "/sportsperformance/news/:year/:month/:path"
  uploads:
    title: Uploads
    output: true
  resources:
    title: resources
    output: true
    permalink: "/sportsperformance/resources/:permalink"
  teams:
    title: Teams
    output: false
  events:
    title: Events
    output: false
  devos:
    title: Devos
    output: true
    permalink: "/sportsperformance/devotionals/:permalink"
  quotes:
    title: Quotes
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    byLine: ''
    layout: page
- scope:
    path: ''
    type: posts
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: devos
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: resources
  values:
    type:
    layout: page
    address: 
    type:
- scope:
    path: ''
    type: teams
  values:
    level: 
    director:
    director_email:
    dates:
    type:
    layout: page
- scope:
    path: ''
    type: events
  values:
    location: 
    image:
    start_date:
    end_date:
    layout: page
    alt_url: 
    short_description:
    final_four:
include: ["_pages"]
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
url: 
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
sass:
  style: compressed
pagination:
  enabled: true
  debug: false
  collection: all
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: index
plugins:
- jekyll-redirect-from
- jekyll-paginate-v2

