---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resources
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _events
  label: Opportunities
  create: all
  match: "**/*"
  templates:
  - opportunity
- type: jekyll-posts
  label: Blog
  create: all
  templates:
  - blog-post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
