---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: documents
  match: "*.md"
  new_doc_ext: ".md"
  templates:
  - home-page-builder
  - page
  - page-builder
- type: jekyll-posts
  label: News
  create: all
  templates:
  - blog-post
- type: directory
  path: _events
  label: Opportunities
  create: all
  match: "**/*"
  templates:
  - opportunity
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resources
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
