---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
- path: ''
  label: Pages
  create: all
- path: _events
  label: Events
  create: all
- path: _teams
  label: Teams
  create: all
- path: _camps
  label: Camps
  create: all
- path: _uploads
  label: Uploads
  create: all
- path: _posts
  label: Posts
  create: all
- path: _media
  label: Media
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
